spring.datasource.url=jdbc:mysql://localhost:3306/Stock

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

twelvedata.api-key= 0184e913178c48c89069f5432106ba53

server.port=8080

